---
version: 2.1

orbs:
  codecov: codecov/codecov@1.0.4

jobs:
  build:
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run:
          name: Run Tests
          command: |
            go test -v -cover -race -coverprofile=coverage.txt -covermode=atomic ./...
      - codecov/upload
