---
version: 2.1

orbs:
  codecov: codecov/codecov@1.0.4

executors:
  golang:
    docker:
      - image: circleci/golang:latest

jobs:
  build:
    executor: golang
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-pkg-mod
      - run:
          name: Run Tests
          command: |
            go test -v -cover -race -coverprofile=coverage.txt -covermode=atomic ./...
      - codecov/upload
      - save_cache:
          key: go-pkg-mod
          paths:
            - "/go/pkg/mod"

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
